module.exports = (config) => {
  config.set({
    listenAddress: 'localhost',
    hostname: 'localhost',
    browsers: ['ChromeHeadless'],
    frameworks: ['mocha'],
    coverageIstanbulReporter: {
      reports: ['json'],
      dir: '.nyc_output',
      fixWebpackSourcePaths: true,
    },
    reporters: ['spec', 'coverage-istanbul'],
    files: ['test/browser/index-webpack.ts'],
    preprocessors: { 'test/browser/index-webpack.ts': ['webpack']},
    webpack: {
      mode: 'development',
      target: 'web',
      output: { filename: 'bundle.js' },
      resolve: { extensions: ['.ts', '.js'] },
      devtool: 'inline-source-map',
      module: {
        rules: [
          { test: /\.ts$/, use: 'ts-loader' },
          {
            enforce: 'post',
            exclude: [
              /(node_modules|test|\.test\.[tj]sx?$)/,
              /(index-webpack.ts$)/,
            ],
            test: /\.ts$/,
            use: {
              loader: 'istanbul-instrumenter-loader',
              options: { esModules: true },
            },
          },
          {
            parser: {
              node: {
                assert: true,
                global: true,
                Buffer: false,
                __dirname: false,
                __filename: false,
                buffer: false,
                child_process: false,
                cluster: false,
                console: false,
                constants: false,
                crypto: false,
                dgram: false,
                dns: false,
                domain: false,
                events: false,
                fs: false,
                http: false,
                https: false,
                module: false,
                net: false,
                os: false,
                path: false,
                process: false,
                punycode: false,
                querystring: false,
                readline: false,
                repl: false,
                setImmediate: false,
                stream: false,
                string_decoder: false,
                sys: false,
                timers: false,
                tls: false,
                tty: false,
                url: false,
                util: false,
                vm: false,
                zlib: false,
              },
            },
          },
        ],
      },
    },
    webpackMiddleware: { noInfo: true },
  });
};
